services:
  skeleton-app:
    depends_on:
      - vox-server
    image: node:22.14.0-slim
    ports:
      - 5173:5173
    environment:
      VITE_VOX_BASE_URL: http://vox-server:8000
    working_dir: /app
    volumes:
      - ./skeleton-app:/app
      - skeleton-app-node-modules:/app/node_modules
    command: /bin/sh -c "npm install && npm run dev"

  vox-server:
    platform: linux/amd64
    build:
      context: ./vox-server
      target: development
      args:
        PLATFORM: linux
        PYTHON_VERSION: 3.11.11
    ports:
      - 8000:8000
    environment:
      VOICEVOX_CORE_PATH: "./voicevox_core"
    volumes:
      - ./vox-server/src:/app/src
      - vox-server-venv:/app/.venv
    command:
      ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--log-config", "src/logging.ini", "--reload"]
    tty: true

volumes:
  skeleton-app-node-modules:
  vox-server-venv:
